baseURL = "https://forestry-with-hugo.pages.dev/"
languageCode = "fi-fi"
summaryLength = 20
theme = "paper"
title = "Forestry + Hugo"
[[menu.main]]
name = "Blogi"
url = "/blogi/"
weight = 2
[[menu.main]]
name = "Etusivu"
url = "/"
weight = 1
